version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/usr/share/nginx/html/index.php
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./index.php:/usr/share/nginx/html/index.php